name: Build / Test

on:
  push:
    branches: [ main ]
    paths: [ 'src/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'src/**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Htc.EfCoreExtensions.sln
    - name: Build
      run: dotnet build src/Htc.EfCoreExtensions.sln --no-restore
    - name: Test
      run: dotnet test src/Htc.EfCoreExtensions.Tests/Htc.EfCoreExtensions.Tests.csproj --no-build --verbosity normal
