name: .NET

on:
  push:
    tags:
      - 'v*.*.*.*'

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore src/Htc.EfCoreExtensions/Htc.EfCoreExtensions.csproj
    - name: Pack
      run: dotnet pack src/Htc.EfCoreExtensions/Htc.EfCoreExtensions.csproj --no-restore --configuration Release -p:PackageVersion=$RELEASE_VERSION
    - name: Deploy
      run: dotnet nuget push "bin/Release/OctocatApp.$RELEASE_VERSION.nupkg"  --api-key ${{secrets.GH_KEY}} --source "github"
